[2018-03-12 09:14:36.980] [ERROR] normal - Error: CAS 验证失败，无法找到 name 和 user 字段，返回的数据为：
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationFailure code="INVALID_SERVICE">Ticket &#39;ST-48227-xHFaPGs4CKwEEB0Dv_bmjCOu0xM-5bc5b775e388&#39; does not match supplied service. The original service was &#39;http://127.0.0.1:3000/api/login&#39; and the supplied service was &#39;http://172.26.6.2:3000/api/login&#39;.</cas:authenticationFailure>
</cas:serviceResponse>

    at Object.getUserInfo$ (/Users/zhangxin/yiconl/src/src/controller/modules/login.js:66:13)
    at tryCatch (/Users/zhangxin/yiconl/src/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/zhangxin/yiconl/src/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/zhangxin/yiconl/src/node_modules/regenerator-runtime/runtime.js:114:21)
    at onFulfilled (/Users/zhangxin/yiconl/src/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
[2018-03-12 10:39:28.283] [INFO] normal - ==> 🐸  Server listening on port 3000
[2018-03-12 10:39:28.423] [INFO] normal - Connection has been established successfully.
